Update build-pipeline.yml

diff --git a/.github/workflows/build-pipeline.yml b/.github/workflows/build-pipeline.yml
--- a/.github/workflows/build-pipeline.yml
+++ b/.github/workflows/build-pipeline.yml
@@ -1,5 +1,5 @@
 name: Run Unit Tests on PR
-
+# commenting until i figure out billing
 on:
   pull_request:
   push:
@@ -8,47 +8,47 @@ on:
       - develop
   workflow_dispatch:
 
-jobs:
-  test:
-    name: Run .NET Unit Tests
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: "8.0"
-
-      - name: Restore dependencies
-        run: dotnet restore
-        working-directory: ./src
-
-      - name: Build Solution
-        run: dotnet build --configuration Release --no-restore
-        working-directory: ./src
-
-      - name: Run Unit Tests with Report
-        run: dotnet test --configuration Release --logger "trx" --results-directory ./TestResults/
-        working-directory: ./src
-        
-      - name: Publish Test Results to PR
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: .NET Unit Tests
-          path: ./src/TestResults/**/*.trx  
-          reporter: dotnet-trx
-          
-      - name: Run Tests with Coverage
-        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
-        working-directory: ./src
-
-      - name: Debug - List test result files
-        run: ls -R ./src/TestResults
-
+#jobs:
+#  test:
+#    name: Run .NET Unit Tests
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Setup .NET
+#        uses: actions/setup-dotnet@v3
+#        with:
+#          dotnet-version: "8.0"
+#
+#      - name: Restore dependencies
+#        run: dotnet restore
+#        working-directory: ./src
+#
+#      - name: Build Solution
+#        run: dotnet build --configuration Release --no-restore
+#        working-directory: ./src
+#
+#      - name: Run Unit Tests with Report
+#        run: dotnet test --configuration Release --logger "trx" --results-directory ./TestResults/
+#        working-directory: ./src
+#        
+#      - name: Publish Test Results to PR
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: .NET Unit Tests
+#          path: ./src/TestResults/**/*.trx  
+#          reporter: dotnet-trx
+#          
+#      - name: Run Tests with Coverage
+#        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
+#        working-directory: ./src
+#
+#      - name: Debug - List test result files
+#        run: ls -R ./src/TestResults
+#
 #      - name: Upload Coverage to Codecov
 #        uses: codecov/codecov-action@v3
 #        with:
